### PR TITLE
Merge `series/0.9` into `main`

### PR DESCRIPTION
**Pull request by amesgen**

### CODE REVIEW

**Comment by armanbilge** [comment]
Huh, I don't understand why this is hanging.

**Comment by armanbilge** [comment]
Maybe this needs a fix that will be in the next milestone, but I don't know what that could be.
- https://github.com/http4s/http4s/pull/7115

**Comment by armanbilge** [comment]
@amesgen finally we can land this one haha.

**Comment by amesgen** [comment]
Sorry for being unresponsive recently, will look at this soon :pray:

**Comment by amesgen** [comment]
Superseded by #1012

**Comment by amesgen** [comment]
I think this can now be merged (does not have the cleanest commit history, but I think it is fine).

**Review by armanbilge — APPROVED** [review]

**Pull request merged**
